### ISSUE TITLE
Is there an updated way of using wercker on local and the website?

### ISSUE THREAD

**Issue by rlam3** [wercker/getting-started-python#5]
boot2docker is deprecated in favor of docker toolbox

https://github.com/boot2docker/osx-installer/releases

**Comment by derek-adair** [comment]
It should work the same as before, but I use ubuntu so i'm unsure.

**Comment by faiq** [comment]
@rlam3 great catch! we're working on updating our documentation to use `docker toolbox` in favor of `boot2docker`, but that should not make a difference when running this sample application. so i'll close this issue for right now, but if you have any problems with running this application going forward feel free to reopen this issue or to file a new one.

if you're interested, we are discussing the issue [here]( https://github.com/wercker/docs/issues/318#issuecomment-165100003) and you're more than welcome to follow along. 

thanks so much for your interest wercker!
